export enum StorageEnum {
  // 全局设置
  ITHINGS_SYSTEM_SETTING_STORE = 'ITHINGS_SYSTEM_SETTING',
  // token 等信息
  ITHINGS_ACCESS_TOKEN_STORE = 'ITHINGS_ACCESS_TOKEN',
  // 登录信息
  ITHINGS_LOGIN_INFO_STORE = 'ITHINGS_LOGIN_INFO',
  // 语言
  ITHINGS_LANG_STORE = 'ITHINGS_LANG',
  // 当前选择的主题
  ITHINGS_DESIGN_STORE = 'ITHINGS_DESIGN',
  // 工作台布局配置
  ITHINGS_CHART_LAYOUT_STORE = 'ITHINGS_CHART_LAYOUT',
  // 工作台需要保存的数据
  ITHINGS_CHART_STORAGE_LIST = 'ITHINGS_CHART_STORAGE_LIST',
}
